language: node_js
node_js:
  - "node"
yarn: true
cache: yarn
script:
  - yarn lint
  - yarn flow
  - yarn build
  - yarn test
before_deploy:
  - yarn prod
deploy:
  provider: npm
  email: "hsuting0106@gmail.com"
  api_key: $npm_token
  on:
    branch: master
    tags: true
