language: node_js
node_js:
  - "node"
yarn: true
cache: yarn
script:
  - yarn lint
deploy:
  provider: npm
  email: "hsuting0106@gmail.com"
  api_key: $npm_token
  skip_cleanup: true
  on:
    tags: true
